# Generated by Django 5.0 on 2024-01-05 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pojeto',
            new_name='Projeto',
        ),
    ]
